# Generated by Django 3.2.6 on 2021-08-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('appRespuestas', '0001_initial'),
        ('InicioApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
